language: csharp
sudo: false
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
  - windows
before_install:
  - mkdir -p $HOME/dotnet
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://download.visualstudio.microsoft.com/download/pr/b9251194-4118-41cb-ae05-6763fb002e5d/1d398b4e97069fa4968628080b617587/dotnet-sdk-3.0.100-osx-x64.tar.gz ; tar zxf dotnet-sdk-3.0.100-osx-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://download.visualstudio.microsoft.com/download/pr/886b4a4c-30af-454b-8bec-81c72b7b4e1f/d1a0c8de9abb36d8535363ede4a15de6/dotnet-sdk-3.0.100-linux-x64.tar.gz ; tar zxf dotnet-sdk-3.0.100-linux-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://download.visualstudio.microsoft.com/download/pr/a24f4f34-ada1-433a-a437-5bc85fc2576a/7e886d06729949c15c96fe7e70faa8ae/dotnet-sdk-3.0.100-win-x64.zip ; 7z x dotnet-sdk-3.0.100-win-x64.zip -o$HOME/dotnet ; fi
script:
  - $HOME/dotnet/dotnet restore
  - $HOME/dotnet/dotnet build
  - $HOME/dotnet/dotnet publish --configuration Release
