language: csharp
sudo: false
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
  - windows
before_install:
  - mkdir -p $HOME/dotnet
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://download.visualstudio.microsoft.com/download/pr/0f566b2b-47e6-484d-91e5-96d2e48c0466/342c321a2a040b62e0ecf186c4ec9d12/dotnet-sdk-3.1.201-osx-x64.tar.gz ; tar zxf dotnet-sdk-3.1.201-osx-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://download.visualstudio.microsoft.com/download/pr/f65a8eb0-4537-4e69-8ff3-1a80a80d9341/cc0ca9ff8b9634f3d9780ec5915c1c66/dotnet-sdk-3.1.201-linux-x64.tar.gz ; tar zxf dotnet-sdk-3.1.201-linux-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://download.visualstudio.microsoft.com/download/pr/adeab8b1-1c44-41b2-b12a-156442f307e9/65ebf805366410c63edeb06e53959383/dotnet-sdk-3.1.201-win-x64.zip ; 7z x dotnet-sdk-3.1.201-win-x64.zip -o$HOME/dotnet ; fi
script:
  - $HOME/dotnet/dotnet restore
  - $HOME/dotnet/dotnet build
  - $HOME/dotnet/dotnet publish --configuration Release
