language: csharp
sudo: false
dist: trusty
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os:
  - linux
  - osx
  - windows

before_install:
  # Manually install .NET 5.0
  - mkdir -p $HOME/dotnet
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://download.visualstudio.microsoft.com/download/pr/0871336f-9a83-4ce4-80ca-625d03003369/2eb78456e0b106e9515dc03898d3867a/dotnet-sdk-5.0.100-osx-x64.tar.gz ; tar zxf dotnet-sdk-3.1.201-osx-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://download.visualstudio.microsoft.com/download/pr/820db713-c9a5-466e-b72a-16f2f5ed00e2/628aa2a75f6aa270e77f4a83b3742fb8/dotnet-sdk-5.0.100-linux-x64.tar.gz ; tar zxf dotnet-sdk-3.1.201-linux-x64.tar.gz -C $HOME/dotnet ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://download.visualstudio.microsoft.com/download/pr/7b78bdaa-d0ac-41c4-9fdc-5820d7dc79b6/cea499dd314ba6394ccea51a2a2dcda9/dotnet-sdk-5.0.100-win-x64.zip ; 7z x dotnet-sdk-3.1.201-win-x64.zip -o$HOME/dotnet ; fi

script:
  #- $HOME/dotnet/dotnet restore
  #- $HOME/dotnet/dotnet build
  - $HOME/dotnet/dotnet publish --configuration Release
